version: "2"
checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    config:
      threshold: 10
  identical-code:
    enabled: true
    config:
      threshold: 10
plugins:
 rubocop:
  enabled: true
 eslint:
  enabled: true
exclude_patterns:
- "config/"
- "dist/"
- "**/node_modules/"
- "**/test/"
- "**/tests/"
- "**/vendor/"
- "**/*.d.ts"
- "**/package-lock.json"